export type GameCategory =
  | 'parti'
  | 'stratégiai'
  | 'család'
  | 'kooperatív'
  | 'kártya'
  | 'absztrakt'
  | 'dobókockás'
  | 'roguelike';

export type GameComplexity = 'könnyű' | 'közepes' | 'nehéz';

export interface GameSeedInput {
  name: string;
  bggId: number | null;
  category: GameCategory;
  complexity: GameComplexity;
  playersMin: number;
  playersMax: number;
  playtimeMinMinutes: number;
  playtimeMaxMinutes: number;
  minAge: number;
  price: number;
  salePrice: number | null;
  stock: number;
  rating: number;
  reviewsCount: number;
  description: string;
}

export const gamesSeedData: GameSeedInput[] = [
  {
    name: 'Catan',
    bggId: 13,
    category: 'stratégiai',
    complexity: 'közepes',
    playersMin: 3,
    playersMax: 4,
    playtimeMinMinutes: 60,
    playtimeMaxMinutes: 120,
    minAge: 10,
    price: 12000,
    salePrice: 9990,
    stock: 15,
    rating: 7.2,
    reviewsCount: 3500,
    description: 'Klasszikus nyersanyag-kereskedős stratégiai játék, amiben Catan szigetét építed be.',
  },
  {
    name: '7 Wonders',
    bggId: 68448,
    category: 'stratégiai',
    complexity: 'közepes',
    playersMin: 3,
    playersMax: 7,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 45,
    minAge: 10,
    price: 13500,
    salePrice: null,
    stock: 8,
    rating: 7.7,
    reviewsCount: 3600,
    description: 'Civilizációépítő kártyajáték, ahol kártyaszomszédodtól draftolsz és 3 korszakon át fejlődsz.',
  },
  {
    name: 'Terraforming Mars',
    bggId: 167791,
    category: 'stratégiai',
    complexity: 'nehéz',
    playersMin: 1,
    playersMax: 5,
    playtimeMinMinutes: 90,
    playtimeMaxMinutes: 180,
    minAge: 12,
    price: 18500,
    salePrice: null,
    stock: 6,
    rating: 8.4,
    reviewsCount: 4500,
    description: 'Mélyebb stratégiai játék, amiben vállalatod a Marsot teszi lakhatóvá — hosszabb, tartalmasabb parti.',
  },
  {
    name: 'Wingspan',
    bggId: 266192,
    category: 'stratégiai',
    complexity: 'közepes',
    playersMin: 1,
    playersMax: 5,
    playtimeMinMinutes: 40,
    playtimeMaxMinutes: 70,
    minAge: 10,
    price: 16000,
    salePrice: 13990,
    stock: 9,
    rating: 8.1,
    reviewsCount: 3700,
    description: 'Madarakat gyűjtő, gyönyörű illusztrációjú engine-building játék, könnyen tanulható mély rendszerrel.',
  },
  {
    name: 'Splendor',
    bggId: 148228,
    category: 'stratégiai',
    complexity: 'közepes',
    playersMin: 2,
    playersMax: 4,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 30,
    minAge: 10,
    price: 8500,
    salePrice: null,
    stock: 16,
    rating: 7.4,
    reviewsCount: 3300,
    description: 'Ékszerkereskedő-szimulátor: drágakövekért fejlesztéseket veszel, hogy presztízspontokat gyűjts.',
  },
  {
    name: 'Carcassonne',
    bggId: 822,
    category: 'család',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 5,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 45,
    minAge: 7,
    price: 9000,
    salePrice: null,
    stock: 20,
    rating: 7.4,
    reviewsCount: 4200,
    description: 'Lapkalerakós klasszikus, amiben várost, utat és kolostort építve pontozol — gyors tanulási görbével.',
  },
  {
    name: 'Ticket to Ride',
    bggId: 9209,
    category: 'család',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 5,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 60,
    minAge: 8,
    price: 12000,
    salePrice: null,
    stock: 14,
    rating: 7.4,
    reviewsCount: 4100,
    description: 'Vasútvonalakat építesz kontinensen át; egyszerű szabályok, de izgalmas útvonal-versengés.',
  },
  {
    name: 'Colt Express',
    bggId: 158899,
    category: 'család',
    complexity: 'közepes',
    playersMin: 2,
    playersMax: 6,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 40,
    minAge: 10,
    price: 11500,
    salePrice: null,
    stock: 7,
    rating: 7.5,
    reviewsCount: 1900,
    description: 'Vonatrablós programozós játék papír-vasút díszlettel; kaotikus, vicces, taktikus fordulókkal.',
  },
  {
    name: 'Kingdomino',
    bggId: 204583,
    category: 'család',
    complexity: 'közepes',
    playersMin: 2,
    playersMax: 4,
    playtimeMinMinutes: 15,
    playtimeMaxMinutes: 20,
    minAge: 8,
    price: 6500,
    salePrice: null,
    stock: 22,
    rating: 7.3,
    reviewsCount: 2200,
    description: 'Dominó-elven épülő királyságépítő; gyors parti, de a lapkaválasztás sorrendje meglepően taktikus.',
  },
  {
    name: 'Cluedo',
    bggId: 11,
    category: 'család',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 6,
    playtimeMinMinutes: 45,
    playtimeMaxMinutes: 45,
    minAge: 8,
    price: 6000,
    salePrice: null,
    stock: 17,
    rating: 6.5,
    reviewsCount: 1500,
    description: 'A klasszikus dedukciós nyomozós társasjáték: ki, mivel és hol követte el a gyilkosságot.',
  },
  {
    name: 'Azul',
    bggId: 230802,
    category: 'absztrakt',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 4,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 45,
    minAge: 8,
    price: 11000,
    salePrice: 8990,
    stock: 12,
    rating: 7.8,
    reviewsCount: 3900,
    description: 'Csempemintázó absztrakt játék: portugál azulejo csempékből raksz ki mintát a palotádon.',
  },
  {
    name: 'Patchwork',
    bggId: 163412,
    category: 'absztrakt',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 2,
    playtimeMinMinutes: 15,
    playtimeMaxMinutes: 30,
    minAge: 8,
    price: 8000,
    salePrice: 6990,
    stock: 13,
    rating: 7.7,
    reviewsCount: 2400,
    description: 'Kétszemélyes patchwork-varrás: tetris-szerű darabokból rakod ki a legjobban kitöltött takarót.',
  },
  {
    name: 'Santorini',
    bggId: 194655,
    category: 'absztrakt',
    complexity: 'közepes',
    playersMin: 2,
    playersMax: 4,
    playtimeMinMinutes: 20,
    playtimeMaxMinutes: 30,
    minAge: 8,
    price: 9500,
    salePrice: null,
    stock: 10,
    rating: 7.3,
    reviewsCount: 1700,
    description: 'Építkezős absztrakt játék egyedi isteni képességekkel; sakkszerű mélység, egyszerű alapszabályokkal.',
  },
  {
    name: 'Onitama',
    bggId: 160477,
    category: 'absztrakt',
    complexity: 'közepes',
    playersMin: 2,
    playersMax: 2,
    playtimeMinMinutes: 15,
    playtimeMaxMinutes: 20,
    minAge: 8,
    price: 7000,
    salePrice: null,
    stock: 11,
    rating: 7.4,
    reviewsCount: 1300,
    description: 'Minimalista, sakkra hajazó kétszemélyes absztrakt duell, elforgatható mozgáskártyákkal.',
  },
  {
    name: 'Quoridor',
    bggId: 624,
    category: 'absztrakt',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 4,
    playtimeMinMinutes: 15,
    playtimeMaxMinutes: 20,
    minAge: 8,
    price: 6500,
    salePrice: null,
    stock: 16,
    rating: 6.6,
    reviewsCount: 1100,
    description: 'Falépítős pályajáték: érj el elsőként a másik oldalra, miközben az ellenfeled útját blokkolod.',
  },
  {
    name: 'Dixit',
    bggId: 39856,
    category: 'parti',
    complexity: 'könnyű',
    playersMin: 3,
    playersMax: 6,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 45,
    minAge: 8,
    price: 9500,
    salePrice: null,
    stock: 18,
    rating: 7.3,
    reviewsCount: 2900,
    description: 'Asszociációs kártyajáték gyönyörű, szürreális illusztrációkkal; a lényeg a jó félrevezetés.',
  },
  {
    name: 'Codenames',
    bggId: 178900,
    category: 'parti',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 8,
    playtimeMinMinutes: 15,
    playtimeMaxMinutes: 30,
    minAge: 14,
    price: 7500,
    salePrice: null,
    stock: 25,
    rating: 7.6,
    reviewsCount: 3800,
    description: 'Csapatos szóasszociációs parti játék: egy szóval kell eltaláltatni több mezőt is egyszerre.',
  },
  {
    name: 'Dobble',
    bggId: 63268,
    category: 'parti',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 8,
    playtimeMinMinutes: 15,
    playtimeMaxMinutes: 15,
    minAge: 6,
    price: 4500,
    salePrice: null,
    stock: 30,
    rating: 6.9,
    reviewsCount: 2500,
    description: 'Gyors reakciójáték: minden két kártyán pontosan egy közös szimbólum van, azt kell megtalálni.',
  },
  {
    name: 'Szóváltó',
    bggId: null,
    category: 'parti',
    complexity: 'könnyű',
    playersMin: 3,
    playersMax: 8,
    playtimeMinMinutes: 20,
    playtimeMaxMinutes: 30,
    minAge: 10,
    price: 5500,
    salePrice: null,
    stock: 9,
    rating: 6.8,
    reviewsCount: 140,
    description: 'Kisebb hazai kiadó szóalkotó parti játéka: körönként egy titkos szótag köré épül a kör.',
  },
  {
    name: 'Bang!',
    bggId: 3955,
    category: 'kártya',
    complexity: 'közepes',
    playersMin: 4,
    playersMax: 7,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 45,
    minAge: 10,
    price: 7000,
    salePrice: null,
    stock: 11,
    rating: 7.0,
    reviewsCount: 2100,
    description: 'Vadnyugati szerepekre épülő bluffolós kártyajáték: seriff, zsiványok, aljas és a renegát csapnak össze.',
  },
  {
    name: 'Love Letter',
    bggId: 129622,
    category: 'kártya',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 4,
    playtimeMinMinutes: 20,
    playtimeMaxMinutes: 20,
    minAge: 10,
    price: 3500,
    salePrice: null,
    stock: 24,
    rating: 7.0,
    reviewsCount: 2600,
    description: 'Mindössze 16 lapos, gyors dedukciós kártyajáték az udvari szerelmeslevél kézbesítéséről.',
  },
  {
    name: 'Sushi Go!',
    bggId: 133473,
    category: 'kártya',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 5,
    playtimeMinMinutes: 15,
    playtimeMaxMinutes: 15,
    minAge: 8,
    price: 4500,
    salePrice: null,
    stock: 21,
    rating: 7.1,
    reviewsCount: 2000,
    description: 'Gyors draftolós kártyajáték: forgó kézből válogass össze egy nyerő sushi-menüt.',
  },
  {
    name: 'Fokhagymás Csata',
    bggId: null,
    category: 'kártya',
    complexity: 'közepes',
    playersMin: 2,
    playersMax: 5,
    playtimeMinMinutes: 25,
    playtimeMaxMinutes: 35,
    minAge: 10,
    price: 6000,
    salePrice: null,
    stock: 6,
    rating: 6.9,
    reviewsCount: 95,
    description: 'Kisebb kiadós kártyacsata-játék, ahol vámpírűző fokhagyma-kombókkal írhatsz felül ellenfeled lapjait.',
  },
  {
    name: 'Pandemic',
    bggId: 30549,
    category: 'kooperatív',
    complexity: 'közepes',
    playersMin: 2,
    playersMax: 4,
    playtimeMinMinutes: 45,
    playtimeMaxMinutes: 60,
    minAge: 10,
    price: 10500,
    salePrice: 8990,
    stock: 10,
    rating: 7.6,
    reviewsCount: 4300,
    description: 'A klasszikus kooperatív játék: csapatként kell megfékezni négy világjárványt, mielőtt elszabadulnak.',
  },
  {
    name: 'Forbidden Island',
    bggId: 65244,
    category: 'kooperatív',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 4,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 30,
    minAge: 10,
    price: 7500,
    salePrice: null,
    stock: 12,
    rating: 7.1,
    reviewsCount: 1500,
    description: 'Könnyed belépő a kooperatív játékokba: süllyedő szigetről kell kincseket menteni csapatban.',
  },
  {
    name: 'Hanabi',
    bggId: 98778,
    category: 'kooperatív',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 5,
    playtimeMinMinutes: 25,
    playtimeMaxMinutes: 25,
    minAge: 8,
    price: 4500,
    salePrice: 3990,
    stock: 15,
    rating: 7.1,
    reviewsCount: 1900,
    description: 'Különleges kooperatív kártyajáték: saját lapjaidat nem látod, csak társaid jelzéseiből következtetsz.',
  },
  {
    name: 'The Crew',
    bggId: 284083,
    category: 'kooperatív',
    complexity: 'közepes',
    playersMin: 2,
    playersMax: 5,
    playtimeMinMinutes: 20,
    playtimeMaxMinutes: 20,
    minAge: 10,
    price: 6000,
    salePrice: null,
    stock: 13,
    rating: 7.9,
    reviewsCount: 2100,
    description: 'Kooperatív ütéses kártyajáték kommunikációs tilalommal — küldetésről küldetésre nehezedő kampány.',
  },
  {
    name: 'Ghost Stories',
    bggId: 26363,
    category: 'kooperatív',
    complexity: 'nehéz',
    playersMin: 1,
    playersMax: 4,
    playtimeMinMinutes: 60,
    playtimeMaxMinutes: 60,
    minAge: 13,
    price: 12500,
    salePrice: null,
    stock: 4,
    rating: 7.6,
    reviewsCount: 1200,
    description: 'Brutálisan nehéz kooperatív játék: taoista papokként kell megvédeni a falut a szellemek inváziójától.',
  },
  {
    name: 'Camel Up',
    bggId: 153938,
    category: 'dobókockás',
    complexity: 'közepes',
    playersMin: 2,
    playersMax: 8,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 45,
    minAge: 8,
    price: 9000,
    salePrice: 7490,
    stock: 8,
    rating: 7.3,
    reviewsCount: 1400,
    description: 'Tevefogadós party-game kockadobással: kire fogadsz, melyik teve ér célba elsőként a piramison át.',
  },
  {
    name: 'King of Tokyo',
    bggId: 70323,
    category: 'dobókockás',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 6,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 30,
    minAge: 8,
    price: 9500,
    salePrice: null,
    stock: 14,
    rating: 7.2,
    reviewsCount: 2700,
    description: 'Óriásszörnyekkel Tokióért vívott kockacsata; egyszerű szabályok, gyors, hangos partik.',
  },
  {
    name: 'Qwixx',
    bggId: 131357,
    category: 'dobókockás',
    complexity: 'könnyű',
    playersMin: 2,
    playersMax: 5,
    playtimeMinMinutes: 15,
    playtimeMaxMinutes: 15,
    minAge: 8,
    price: 4000,
    salePrice: null,
    stock: 25,
    rating: 7.0,
    reviewsCount: 1300,
    description: 'Gyors kockás pontozójáték: mindenki egyszerre játszik, nincs várakozás a köröd között.',
  },
  {
    name: "Aeon's End",
    bggId: 191189,
    category: 'roguelike',
    complexity: 'nehéz',
    playersMin: 1,
    playersMax: 4,
    playtimeMinMinutes: 60,
    playtimeMaxMinutes: 90,
    minAge: 14,
    price: 17500,
    salePrice: null,
    stock: 3,
    rating: 8.2,
    reviewsCount: 2200,
    description: 'Deckbuilding kooperatív dungeon-crawler forduló sorrenddel; kemény taktikai kihívás, roguelike hangulattal.',
  },
  {
    name: 'Gloomhaven',
    bggId: 174430,
    category: 'roguelike',
    complexity: 'nehéz',
    playersMin: 1,
    playersMax: 4,
    playtimeMinMinutes: 90,
    playtimeMaxMinutes: 150,
    minAge: 14,
    price: 32000,
    salePrice: null,
    stock: 2,
    rating: 8.6,
    reviewsCount: 4300,
    description: 'Kampányalapú roguelike dungeon-crawler dobozban: több tucat küldetés, fejlődő karakterek, hatalmas doboz.',
  },
  {
    name: 'Too Many Bones',
    bggId: 244992,
    category: 'roguelike',
    complexity: 'nehéz',
    playersMin: 1,
    playersMax: 4,
    playtimeMinMinutes: 60,
    playtimeMaxMinutes: 120,
    minAge: 14,
    price: 24000,
    salePrice: null,
    stock: 0,
    rating: 8.3,
    reviewsCount: 1500,
    description: 'Kockaépítős roguelike harcjáték egyedi Gearloc hősökkel; jelenleg elfogyott, utánrendelés alatt.',
  },
  {
    name: 'Kazamata Kártyák',
    bggId: null,
    category: 'roguelike',
    complexity: 'közepes',
    playersMin: 1,
    playersMax: 4,
    playtimeMinMinutes: 30,
    playtimeMaxMinutes: 50,
    minAge: 12,
    price: 9500,
    salePrice: null,
    stock: 0,
    rating: 7.2,
    reviewsCount: 60,
    description: 'Kisebb kiadós roguelike kártyás dungeon-crawler: procedurálisan épülő kazamaták, gyors szólópartikra is.',
  },
];
